/* ============================================================================
   English source strings for the Riposte Laboratories site (all four pages).
   One key = one translatable unit. Values may contain inline HTML that MUST be
   preserved verbatim in translations: <b>, <i>, <sup class="fn">…</sup> footnote
   refs, <a href> links, and numeric HTML entities (&#183; = ·, &#215; = ×,
   &#8594; = →, &#9851; = ♻, &#9993; = ✉, &#8211; = –, &#9888; = ⚠).
   Proper nouns kept as-is across all languages: Riposte Laboratories, Riposte,
   Project HEX, HEX, esh, Plastic Works, Gunpla, Best Buy, Merlin Plastics.
   Product/section codes (RL-P01, SEC.01), numbers, units and URLs are NOT
   translated. Generated JSON for other languages lives beside this file.
   ============================================================================ */
module.exports = {
  /* ---- shared chrome ---- */
  "nav.home": "Home",
  "nav.process": "Process",
  "nav.recycling101": "Recycling 101",
  "nav.deck": "Deck",
  "nav.company": "Company",
  "nav.projects": "Projects",
  "nav.mission": "Mission",
  "nav.esh": "Meet Esh",
  "nav.contact": "Contact",
  "nav.plastics": "Plastic Works",
  "nav.hex": "Project HEX",
  "nav.ourprocess": "Our Process",
  "chrome.version": "Version",
  "chrome.language": "Language",
  "chrome.full": "Full",
  "chrome.mobile": "Mobile",
  "chrome.lite": "Lite",
  "chrome.eink": "E-ink",
  "chrome.fullsite": "Full site",
  "chrome.skip": "Skip to content",
  "chrome.mtnote": "Machine translation. English is the original.",
  "chrome.lightweight": "Lightweight versions:",
  "chrome.readerview": "reader view",
  "footer.rights": "&copy; 2026 Riposte Laboratories Inc. &#183; All rights reserved.",
  "footer.loop": "parry &#9851; riposte &#9851; recycle &#9851; repeat",

  /* ---- home ---- */
  "home.title": "Parry. Riposte.",
  "home.desc": "Riposte Laboratories counter-attacks the problems plaguing our world: recycled plastic injection molding and reclaimed-cell modular power.",
  "home.eyebrow": "Laboratories Inc.",
  "home.h1a": "The world attacks.",
  "home.h1b": "We riposte.",
  "home.sub": "An engineering company that transforms discarded plastic and end-of-life battery cells into durable, modular products.",
  "home.cta": "See what we do",

  "home.mission.h": "Mission",
  "home.mission.tag": "the counter-attack",
  "home.mission.def": "<b>riposte</b> <span class=\"defn\">/r&#618;&#712;po&#650;st/ n.</span> In fencing, a quick counter-attack delivered immediately after parrying an opponent's blow.",
  "flow.intake": "Intake", "flow.intake.sub": "(waste stream)",
  "flow.parry": "Parry", "flow.parry.sub": "(collect + sort)",
  "flow.riposte": "Riposte", "flow.riposte.sub": "(re-engineer)",
  "flow.return": "Return", "flow.return.sub": "(finished product)",
  "home.mission.p1": "Canada discards <b>5,152 kt</b> of plastic a year and reprocesses only about <b>6.5%</b><sup class=\"fn\"><a href=\"#fn1\">1</a></sup> of it; batteries and devices are binned with most of their service life still inside. Riposte Laboratories was founded to <span class=\"hi\">address that directly</span>: recovering material from the waste stream and returning it as durable, well-engineered products.",
  "home.mission.p2": "We operate at a local scale: recovering materials that would otherwise be discarded, engineering them into functional products, and returning them to the communities they came from.",

  "home.plastics.h": "Plastic Works",
  "home.plastics.tag": "local loop injection molding",
  "home.plastics.lead": "Plastic is collected from local sources, then shredded, sorted, and remanufactured through injection molding.",
  "home.plastics.spec.h": "SPEC / PLASTIC LOOP",
  "home.plastics.spec.1": "Feedstock: clean post-industrial PS &amp; ABS (model-kit runners)",
  "home.plastics.spec.2": "Process: shred &#8594; sort &#8594; dry &#8594; injection mold",
  "home.plastics.spec.3": "Output: durable repurposed goods, molded in-house",
  "home.plastics.spec.4": "Radius: local. Collected here, remade here, used here",
  "home.plastics.spec.5": "Principle: keep material in use, close to home",
  "home.plastics.p1": "Post-industrial PS and ABS (the resins in every model kit) are clean, single-resin, and homogeneous<sup class=\"fn\"><a href=\"#fn2\">2</a></sup>, yet no BC program takes plastics from business and no local buyer pays for them<sup class=\"fn\"><a href=\"#fn3\">3</a></sup>. We keep that loop local: community-scale collection, in-house processing, and molded products returned to the area they came from.",
  "home.plastics.p2": "Short supply loops. Long-lived products. No ocean freight.",

  "home.hex.h": "Project HEX",
  "home.hex.tag": "modular reclaimed power",
  "home.hex.lead": "Project HEX turns reclaimed lithium cells into a modular hexagonal power tile: an energy panel that clips into arrays and clads the surface of a building.",
  "home.hex.spec.h": "SPEC / HEX UNIT",
  "home.hex.spec.1": "Cells: 6 &#215; cylindrical Li-ion, 45 &#215; 13 mm &#183; reclaimed and graded",
  "home.hex.spec.2": "Topology: one cell per edge, wired 6S (series)",
  "home.hex.spec.3": "Energy: 6 &#215; 2.41 Wh = <b>14.46 Wh</b> per tile",
  "home.hex.spec.4": "Top face: integrated photovoltaic panel &#183; self-charging",
  "home.hex.spec.5": "Edges: magnetic &#183; tiles snap into tessellating arrays",
  "home.hex.spec.6": "Accessory: magnet-mounted screen for interface + telemetry",
  "home.hex.spec.7": "Geometry: hexagonal, tessellates over geodesic structures",
  "home.hex.spec.8": "Status: <b>in development</b> &#183; patent pending",
  "home.hex.p1": "Each unit carries six cylindrical cells measuring <b>45 &#215; 13 mm</b>, one seated along every edge of the hexagon and wired <span class=\"hi\">in series</span>. Six reclaimed 2.41 Wh cells deliver <b>14.46 Wh</b> per tile at a 6S output.",
  "home.hex.p2": "The top face is a solar panel, so every tile is a small generator that tops up its own cells. Magnetic edges let units snap together, and those same magnets accept an optional screen module to interface with the array.",
  "home.hex.p3": "Because hexagons tessellate, arrays scale without gaps and wrap compound curves; the geometry is built to sheath a <span class=\"hi\">geodesic-based home</span> in self-charging power.",
  "home.hex.stamp": "Patent pending &#183; RL-H series",

  "home.esh.h": "Meet Esh",
  "home.esh.tag": "company emblem",
  "home.esh.lead": "The figure integrated into our wordmark is <b>esh</b> (she/her), the emblem of Riposte Laboratories.",
  "home.esh.spec.h": "DOSSIER / ESH",
  "home.esh.spec.1": "Role: company emblem",
  "home.esh.spec.2": "Pronouns: she/her",
  "home.esh.spec.3": "Represents: precision, speed, the counter-attack",
  "home.esh.spec.4": "Pattern: checkered",
  "home.esh.spec.5": "Status: mid-riposte",
  "home.esh.p1": "Esh represents the principles behind our name: precision, speed, and deliberate action; serious engineering carried out with a distinct identity.",

  "home.contact.h": "Contact",
  "home.contact.tag": "get in touch",
  "home.contact.lead": "Whether you have plastic to divert, devices to recycle, or a project to discuss, we would be glad to hear from you.",

  "sources.h": "Sources",
  "sources.tag": "data references",
  "src.statcan": "Statistics Canada &#183; Physical flow account for plastic material, 2022 (released 2026): 5,152 kt discarded, roughly 6.5% reprocessed into pellets, flakes and fibres. <a href=\"https://www150.statcan.gc.ca/n1/daily-quotidien/260326/dq260326e-eng.htm\">statcan.gc.ca</a>",
  "src.apr": "Association of Plastic Recyclers &#183; post-industrial resin is typically cleaner and more homogeneous, with higher market value than post-consumer material. <a href=\"https://plasticsrecycling.org/resources/is-all-recycled-material-created-equal/\">plasticsrecycling.org</a>",
  "src.rcbc": "Recycling Council of BC &#183; no set BC program accepts plastics from business; Merlin Plastics' published buy list covers PET/PP/PE but omits PS and ABS. <a href=\"https://rcbc.ca/our-faqs/where-can-i-recycle-plastics-from-my-business/\">rcbc.ca</a> &#183; <a href=\"https://merlinplastics.com/\">merlinplastics.com</a>",

  /* ---- process ---- */
  "process.title": "Our Process",
  "process.desc": "How Riposte Laboratories collects material: a local drop-off partner network. Model-kit runners and sprues from hobby stores; lithium cells from repair shops, vape retailers, and electronics stores.",
  "process.kicker": "Operations // DOC NO. RL-200-A",
  "process.h1": "Our Process",
  "process.intro": "We do not ask people to find us. We meet material where it already ends up, at the businesses it came from. Our collection runs on a network of local drop-off partners, each hosting a bin for the specific waste stream their customers generate.",

  "process.model.h": "The Drop-off Model",
  "process.model.tag": "collect at the point of sale",
  "process.model.lead": "We partner with local businesses as drop-off points for the recyclable materials that were originally part of a purchase they made.",
  "process.model.spec.h": "SPEC / COLLECTION MODEL",
  "process.model.spec.1": "Model: hosted drop-off bins at partner businesses",
  "process.model.spec.2": "Origin: material returns to its own point of sale",
  "process.model.spec.3": "Radius: local. Collected here, processed here, used here",
  "process.model.spec.4": "Sorting: streams kept separate at intake",
  "process.model.spec.5": "Partner cost: none; we supply and service the bins",
  "process.model.p1": "The material a business sells often comes back through its own door as waste: an offcut, a spent cell, an end-of-life device. Rather than build a separate collection system, we place a bin at that natural return point and <span class=\"hi\">close the loop where it starts</span>.",
  "process.model.p2": "For the customer, dropping off is as convenient as the original purchase. For the partner, it is a visible commitment to keeping material out of landfill. For us, it means a clean, predictable, pre-sorted supply.",
  "flow.partner": "Partner", "flow.partner.sub": "(host a bin)",
  "flow.collect": "Collect", "flow.collect.sub": "(customers return)",
  "flow.riposte2.sub": "(sort + re-engineer)",

  "process.plastic.h": "Plastic Stream",
  "process.plastic.tag": "runners &amp; sprues from hobby stores",
  "process.plastic.lead": "Our plastic feedstock comes from scale-model kits: the runners and sprues left over once the parts are clipped out.",
  "process.plastic.spec.h": "SPEC / PLASTIC INTAKE",
  "process.plastic.spec.1": "Source: hobby, model-kit, and game stores",
  "process.plastic.spec.2": "Material: runners &amp; sprues &#183; polystyrene / ABS",
  "process.plastic.spec.3": "Condition: clean, dry, uncontaminated by design",
  "process.plastic.spec.4": "Sorting: separated by colour where possible",
  "process.plastic.spec.5": "Market: PS/ABS &#183; no BC buyer pays; nearest are in Ontario<sup class=\"fn\"><a href=\"#fn2\">2</a></sup>",
  "process.plastic.spec.6": "Destination: shred &#8594; sort &#8594; dry &#8594; injection mold",
  "process.plastic.p1": "Every model kit (Gunpla and its relatives) arrives as parts held on a plastic lattice. Once a build is finished, that lattice is discarded. It is one of the cleanest waste streams available: uniform, high-grade polystyrene and ABS, moulded to a known spec, sorted by frame, and free of any food or liquid contamination.",
  "process.plastic.p2": "Hobby and model stores are the ideal partner. Their customers generate a steady supply of this exact offcut, and many builders already save their runners rather than bin them. We place a collection bin in the shop; the material flows straight into our injection-molding loop.",
  "process.plastic.p3": "Post-industrial resin like this is cleaner and more homogeneous than curbside plastic, so it commands a premium<sup class=\"fn\"><a href=\"#fn1\">1</a></sup>, yet no BC program takes plastics from business, and no local buyer pays for PS or ABS<sup class=\"fn\"><a href=\"#fn2\">2</a></sup>. That gap is our feedstock.",

  "process.battery.h": "Battery Stream",
  "process.battery.tag": "cells from repair, vape &amp; retail",
  "process.battery.lead": "Lithium cells accumulate wherever devices are sold or serviced. We partner with those businesses to intercept them.",
  "process.battery.spec.h": "SPEC / CELL INTAKE",
  "process.battery.spec.1": "Sources: phone / IT repair shops",
  "process.battery.spec.2": "Sources: e-cigarette &amp; vape retailers",
  "process.battery.spec.3": "Sources: electronics retailers (e.g. Best Buy)",
  "process.battery.spec.4": "Material: lithium cells from phones, disposables, devices",
  "process.battery.spec.5": "Handling: terminals taped, stored in fire-safe containers",
  "process.battery.spec.6": "Transport: lithium dangerous goods &#183; UN3480 / UN3481, Class 9<sup class=\"fn\"><a href=\"#fn3\">3</a></sup>",
  "process.battery.spec.7": "Destination: Project HEX reclamation + rebuild",
  "process.battery.p1": "End-of-life cells are hazardous in a curbside bin but valuable in the right hands. We collect them through the businesses that handle them every day and route them into <span class=\"hi\">Project HEX</span> for testing, grading, and rebuilding into modular power units.",
  "process.battery.p2": "Three partner types supply this stream:",
  "process.battery.p3": "<b>Phone &amp; IT repair shops</b>: cells pulled during battery replacements and board repairs, otherwise stockpiled or discarded.<br><b>E-cigarette &amp; vape retailers</b>: spent disposables and modules, each holding a lithium cell usually discarded with life still in it.<br><b>Electronics retailers</b>: large stores such as Best Buy that already run take-back programs and gather cells at volume.",
  "process.battery.p4": "BC has no vape take-back today; a producer-funded program is legislated for October 2027, with plans due December 2026; no processor is named yet, even in Quebec's live program<sup class=\"fn\"><a href=\"#fn4\">4</a></sup>. Discarded cells also drove 448 waste-facility fires across the US and Canada in 2025<sup class=\"fn\"><a href=\"#fn5\">5</a></sup>. Intercepting them now is both a safety measure and a head start.",
  "process.battery.stamp": "All cells stored terminals-taped, fire-safe",

  "process.network.h": "Partner Network",
  "process.network.tag": "who hosts a bin",
  "process.network.lead": "Each partner hosts the stream their customers already produce.",
  "process.network.p1.name": "Hobby &amp; Model Stores",
  "process.network.p1.desc": "Model-kit and game shops whose customers finish builds and set aside the leftover lattice.",
  "process.network.p1.drops": "Drops: runners &amp; sprues",
  "process.network.p2.name": "Phone &amp; IT Repair",
  "process.network.p2.desc": "Repair benches that swap failing batteries and accumulate pulled cells with no clean route out.",
  "process.network.p2.drops": "Drops: lithium cells",
  "process.network.p3.name": "Vape Retailers",
  "process.network.p3.desc": "E-cigarette shops collecting spent disposables, each with a sealed lithium cell inside.",
  "process.network.p3.drops": "Drops: disposable cells",
  "process.network.p4.name": "Electronics Retailers",
  "process.network.p4.desc": "Larger stores such as Best Buy with established take-back programs and cells gathered at volume.",
  "process.network.p4.drops": "Drops: mixed device cells",
  "process.network.note.h": "Become a drop-off partner",
  "process.network.note.body": "Run a shop that generates one of these streams? Hosting a bin costs nothing and keeps your customers' material in a local loop. <a href=\"{contact}\">Get in touch</a> to set one up.",

  "src.apr2": "Association of Plastic Recyclers &#183; post-industrial resin is typically cleaner and more homogeneous, with higher market value than post-consumer material. <a href=\"https://plasticsrecycling.org/resources/is-all-recycled-material-created-equal/\">plasticsrecycling.org</a>",
  "src.rcbc2": "Recycling Council of BC &#183; no set BC program accepts plastics from business; Merlin Plastics' buy list omits PS/ABS; the nearest published PS/ABS buyers are in Ontario (EPL Plastics, Kal-Polymers). <a href=\"https://rcbc.ca/our-faqs/where-can-i-recycle-plastics-from-my-business/\">rcbc.ca</a> &#183; <a href=\"https://merlinplastics.com/\">merlinplastics.com</a> &#183; <a href=\"https://eplplastics.ca/\">eplplastics.ca</a>",
  "src.tc": "Transport Canada &#183; used lithium batteries ship as dangerous goods UN3480 / UN3481, Class 9 (TDG). <a href=\"https://tc.canada.ca/en/dangerous-goods/safety-awareness-materials-faq/industry/transporting-batteries\">tc.canada.ca</a>",
  "src.reg": "Recycling Regulation, B.C. Reg. 449/2004 (vapes added Nov 2025; approved plan required Oct 1, 2027, submissions due Dec 15, 2026) and Call2Recycle's draft 2025&#8211;2029 BC plan (launch anticipated H2 2027). Quebec's Call2Recycle program is the only one operating; no processor is publicly named. <a href=\"https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/449_2004\">bclaws.gov.bc.ca</a> &#183; <a href=\"https://call2recycle.ca/british-columbia/\">call2recycle.ca</a>",
  "src.fire": "Fire Rover via Resource Recycling &#183; 448 publicly reported fires at US and Canadian waste and recycling facilities in 2025 (approximately $2.5B in damages); vaping devices cited as a driver. <a href=\"https://resource-recycling.com/e-scrap/2026/03/27/report-pegs-fire-losses-at-2-5b-in-us-and-canada-recycling-industry/\">resource-recycling.com</a>",

  /* ---- recycling 101 ---- */
  "recyc.title": "Recycling 101",
  "recyc.desc": "A practical field guide to recycling every material stream: plastics, paper, glass, metals, batteries, e-waste, organics, and textiles.",
  "recyc.kicker": "Field guide // DOC NO. RL-101-A",
  "recyc.h1": "Recycling 101",
  "recyc.intro": "A practical guide to every major material stream: what belongs in the bin, what doesn't, and why. Rules vary by municipality; treat this page as the fundamentals and your local program as the final word.",
  "recyc.toc.h": "On this page",
  "toc.basics": "The basics", "toc.plastics": "Plastics", "toc.paper": "Paper + cardboard",
  "toc.glass": "Glass", "toc.metal": "Metals", "toc.batteries": "Batteries + e-waste",
  "toc.organics": "Organics", "toc.textiles": "Textiles", "toc.rules": "Golden rules", "toc.sources": "Sources",

  "recyc.basics.h": "The Basics",
  "recyc.basics.tag": "how recycling actually works",
  "recyc.basics.lead": "Recycling is a manufacturing supply chain, not a magic bin.",
  "recyc.basics.p1": "Whatever you put in the bin gets collected, sorted at a materials recovery facility (MRF), baled, and sold as feedstock to manufacturers. If a bale is contaminated (food residue, wrong materials, tangled items), its value drops and it may be landfilled anyway.",
  "recyc.basics.p2": "That's why the rules matter: <b>clean, empty, dry, and loose</b>. One greasy container can spoil an entire bale of paper. Plastic bags jam sorting machinery. When you recycle well, the material actually gets a second life; when you guess, it often doesn't.",
  "recyc.basics.p3": "The scale of the gap is large: Canada discarded <b>5,152 kt</b> of plastic in 2022 and reprocessed only about <b>6.5%</b> of it into new pellets, flakes, and fibres.<sup class=\"fn\"><a href=\"#fn1\">1</a></sup>",
  "recyc.basics.note.h": "Local rules win",
  "recyc.basics.note.body": "Every municipality accepts a different set of materials. Check your local program's list once; it takes five minutes and beats years of guessing.",

  "recyc.plastics.h": "Plastics",
  "recyc.plastics.tag": "know your resin codes",
  "recyc.plastics.lead": "The number in the triangle is a resin code, not a promise of recyclability.",
  "recyc.plastics.p1": "Only some resins have strong recycling markets. Bottles and jugs (#1, #2) are the reliable ones; most programs also take #5 tubs. Film, bags, and foam almost never belong in a curbside bin.",
  "code.1": "bottles, jars: widely accepted",
  "code.2": "jugs, tubs: widely accepted",
  "code.3": "pipes, blister packs: rarely accepted",
  "code.4": "films, bags: store drop-off only",
  "code.5": "tubs, caps: accepted in many programs",
  "code.6": "foam, cutlery: rarely accepted",
  "code.7": "mixed resins: generally not accepted",
  "recyc.plastics.yes.h": "Bin: usually yes",
  "recyc.plastics.yes.1": "Beverage + food bottles and jars (#1)",
  "recyc.plastics.yes.2": "Milk jugs, detergent bottles (#2)",
  "recyc.plastics.yes.3": "Yogurt tubs, takeout containers (#5, check locally)",
  "recyc.plastics.yes.4": "Rinsed, with lids on (most programs)",
  "recyc.plastics.no.h": "Bin: no",
  "recyc.plastics.no.1": "Plastic bags + film (jams sorters; use store drop-off)",
  "recyc.plastics.no.2": "Foam / polystyrene of any kind",
  "recyc.plastics.no.3": "Straws, cutlery, and anything smaller than a credit card",
  "recyc.plastics.no.4": "\"Compostable\" bioplastics (different stream entirely)",
  "recyc.plastics.note.h": "The Riposte angle",
  "recyc.plastics.note.body": "Polystyrene (#6) and ABS (#7), the resins in model kits, have no BC buyer that pays, and no BC program takes plastics from business at all.<sup class=\"fn\"><a href=\"#fn2\">2</a></sup> That clean, single-resin material is exactly what our local-loop injection molding program exists for: we take it and mold it into long-lived products.",

  "recyc.paper.h": "Paper + Cardboard",
  "recyc.paper.tag": "the fibre stream",
  "recyc.paper.lead": "Paper fibre can be recycled five to seven times before it wears out, provided it stays clean and dry.",
  "recyc.paper.p1": "Cardboard is one of the most valuable curbside materials. Flatten boxes so they sort correctly and take less space. Wet or food-soiled fibre can't be recycled: grease physically ruins the pulping process.",
  "recyc.paper.yes.h": "Bin: yes",
  "recyc.paper.yes.1": "Flattened cardboard boxes",
  "recyc.paper.yes.2": "Office paper, mail, newspaper, magazines",
  "recyc.paper.yes.3": "Paperboard (cereal boxes, shoe boxes)",
  "recyc.paper.yes.4": "Clean pizza-box lids (tear off the greasy half)",
  "recyc.paper.no.h": "Bin: no",
  "recyc.paper.no.1": "Grease- or food-soiled paper",
  "recyc.paper.no.2": "Used paper towels, napkins, tissues",
  "recyc.paper.no.3": "Wax- or plastic-coated cups (most programs)",
  "recyc.paper.no.4": "Loose shredded paper (bags of it jam sorters; check locally)",

  "recyc.glass.h": "Glass",
  "recyc.glass.tag": "infinitely recyclable",
  "recyc.glass.lead": "Container glass can be melted and remade forever with no loss of quality.",
  "recyc.glass.p1": "The catch: only <i>container</i> glass. Window panes, drinking glasses, ceramics, and heat-treated glass (like bakeware) have different melting points and ruin batches of new containers. Some municipalities collect glass separately or not at all; check yours.",
  "recyc.glass.yes.h": "Bin: yes",
  "recyc.glass.yes.1": "Bottles: any colour, rinsed",
  "recyc.glass.yes.2": "Food jars, lids removed (recycle metal lids with metals)",
  "recyc.glass.no.h": "Bin: no",
  "recyc.glass.no.1": "Window or mirror glass",
  "recyc.glass.no.2": "Drinking glasses, ceramics, porcelain",
  "recyc.glass.no.3": "Heat-resistant bakeware",
  "recyc.glass.no.4": "Light bulbs (CFLs are hazardous-waste drop-off)",

  "recyc.metal.h": "Metals",
  "recyc.metal.tag": "the highest-value stream",
  "recyc.metal.lead": "Recycling aluminum uses roughly 95% less energy than producing it from ore. It is the recycling success story.",
  "recyc.metal.p1": "Aluminum and steel cans can be recycled indefinitely. Scrap metal (pans, tools, wire) is valuable too, but it belongs at a scrap yard or metal drop-off, not in the curbside bin where it damages equipment.",
  "recyc.metal.yes.h": "Bin: yes",
  "recyc.metal.yes.1": "Aluminum cans, rinsed",
  "recyc.metal.yes.2": "Steel / tin food cans",
  "recyc.metal.yes.3": "Clean aluminum foil, balled up (check locally)",
  "recyc.metal.yes.4": "Empty aerosol cans (most programs)",
  "recyc.metal.no.h": "Bin: no",
  "recyc.metal.no.1": "Scrap metal, tools, cookware (take to scrap yard)",
  "recyc.metal.no.2": "Wire, cables, hangers (tanglers)",
  "recyc.metal.no.3": "Partially full aerosol or propane cans (hazardous)",

  "recyc.batteries.h": "Batteries + E-Waste",
  "recyc.batteries.tag": "never in the bin. ever.",
  "recyc.batteries.lead": "Batteries do not go in any curbside bin, recycling or trash. Crushed lithium cells start fires in trucks and facilities.",
  "recyc.batteries.p1": "Every battery type has a proper drop-off route: household battery collection points, hazardous-waste facilities, and retailer take-back programs. Electronics carry both recoverable metals and hazardous components, so they belong in dedicated e-waste programs.",
  "recyc.batteries.p2": "Disposable vapes are the worst offender: a lithium cell, sealed in plastic, marketed as trash. Most are discarded with the cell still healthy. Embedded cells also make them a fire vector: discarded batteries drove <b>448 waste-facility fires</b> across the US and Canada in 2025, with vapes a named driver.<sup class=\"fn\"><a href=\"#fn3\">3</a></sup> This is the waste stream Project HEX exists to intercept: we collect them, reclaim the cells, and build them into modular solar-topped power units.",
  "recyc.batteries.p3": "Take-back is still patchy in Canada. Quebec runs the only operating vape program (launched 2025); <b>BC has none today</b>, but a producer-funded program is legislated for <b>October 2027</b>.<sup class=\"fn\"><a href=\"#fn4\">4</a></sup> Until then, a household battery drop-off or a specialist collector is the only compliant route.",
  "recyc.batteries.warn.h": "Proper routes",
  "recyc.batteries.warn.1": "Household batteries &#8594; collection points (many retailers)",
  "recyc.batteries.warn.2": "Lithium / rechargeable &#8594; battery take-back programs",
  "recyc.batteries.warn.3": "Phones, laptops, cables &#8594; e-waste drop-off",
  "recyc.batteries.warn.4": "Disposable vapes &#8594; vape take-back, or send them to us",
  "recyc.batteries.no.h": "Never",
  "recyc.batteries.no.1": "Any battery in curbside recycling",
  "recyc.batteries.no.2": "Any battery in household trash",
  "recyc.batteries.no.3": "Electronics in curbside recycling",
  "recyc.batteries.no.4": "Tape-free loose lithium cells (tape the terminals)",
  "recyc.batteries.note.h": "Collecting now",
  "recyc.batteries.note.body": "Riposte Laboratories accepts dead disposable vapes for cell reclamation. <a href=\"{contact}\">Contact us</a> to arrange a drop-off.",

  "recyc.organics.h": "Organics",
  "recyc.organics.tag": "food + yard waste",
  "recyc.organics.lead": "Food waste in a landfill decomposes without oxygen and produces methane, a potent greenhouse gas. Composted, it becomes soil.",
  "recyc.organics.p1": "If your area has green-bin collection, use it for food scraps and yard trimmings. If not, backyard composting handles fruit and vegetable scraps, coffee grounds, eggshells, and leaves. Keep meat, dairy, and oils out of home compost; they attract pests and break down poorly.",
  "recyc.organics.yes.h": "Compost: yes",
  "recyc.organics.yes.1": "Fruit + vegetable scraps, coffee grounds, eggshells",
  "recyc.organics.yes.2": "Yard trimmings, leaves, plain paper (home compost)",
  "recyc.organics.yes.3": "Meat + dairy in municipal green bins (check locally)",
  "recyc.organics.no.h": "Compost: no",
  "recyc.organics.no.1": "Plastic of any kind, including \"compostable\" bioplastic at home",
  "recyc.organics.no.2": "Meat, dairy, oils in backyard piles",
  "recyc.organics.no.3": "Pet waste (pathogens)",

  "recyc.textiles.h": "Textiles",
  "recyc.textiles.tag": "the forgotten stream",
  "recyc.textiles.lead": "Clothing never belongs in the curbside bin, but almost all of it can be reused or recycled through the right channel.",
  "recyc.textiles.p1": "Wearable clothing should be donated or resold. Damaged textiles still have value: many donation centers and dedicated textile-recycling programs accept worn-out items and turn them into insulation, rags, and fibre fill. Landfilling clothing wastes both the material and everything it took to make it.",
  "recyc.textiles.yes.h": "Proper routes",
  "recyc.textiles.yes.1": "Wearable &#8594; donation, resale, repair",
  "recyc.textiles.yes.2": "Damaged &#8594; textile-recycling drop-off (label items \"rags\")",
  "recyc.textiles.yes.3": "Shoes, linens, curtains &#8594; most textile programs take them",
  "recyc.textiles.no.h": "Never",
  "recyc.textiles.no.1": "Any textiles in curbside recycling (tanglers)",
  "recyc.textiles.no.2": "Wet or moldy textiles in donation bins",

  "recyc.rules.h": "Golden Rules",
  "recyc.rules.tag": "if you remember nothing else",
  "recyc.rules.lead": "Five rules cover 95% of good recycling.",
  "recyc.rules.1.t": "Clean, empty, dry", "recyc.rules.1.d": "Rinse containers. One saucy jar can contaminate a whole bale.",
  "recyc.rules.2.t": "Never bag recyclables", "recyc.rules.2.d": "Put items in the bin loose. Bagged loads get landfilled unopened.",
  "recyc.rules.3.t": "No tanglers", "recyc.rules.3.d": "Hoses, cords, wire, textiles, chains: they shut down sorting lines.",
  "recyc.rules.4.t": "Batteries never bin", "recyc.rules.4.d": "Not recycling, not trash. Drop-off only. Fires are not hypothetical.",
  "recyc.rules.5.t": "When in doubt, find out", "recyc.rules.5.d": "Wishcycling does more harm than landfilling. Check your local list.",

  "recyc.sources.lead": "Figures on this page trace to primary Canadian sources.",
  "src.rcbc3": "Recycling Council of BC &#183; no set BC program accepts plastics from business; Merlin Plastics' buy list covers PET/PP/PE but omits PS and ABS. <a href=\"https://rcbc.ca/our-faqs/where-can-i-recycle-plastics-from-my-business/\">rcbc.ca</a> &#183; <a href=\"https://merlinplastics.com/\">merlinplastics.com</a>",
  "src.reg2": "Call2Recycle &#183; Quebec vape program (launched January 2025) and draft 2025&#8211;2029 BC plan; Recycling Regulation, B.C. Reg. 449/2004 (approved BC vape plan required October 1, 2027). <a href=\"https://call2recycle.ca/british-columbia/\">call2recycle.ca</a> &#183; <a href=\"https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/449_2004\">bclaws.gov.bc.ca</a>",

  /* ---- deck (linear reader + slides) ---- */
  "deck.title": "Investor Briefing",
  "deck.desc": "Riposte Laboratories investor briefing: reclaimed material, re-engineered into durable products and modular reclaimed power.",
  "deck.kicker": "Investor briefing // DOC NO. RL-DECK-01 &#183; Confidential",
  "deck.cover.lede": "Reclaimed material, <span class=\"hi\">re-engineered.</span>",
  "deck.cover.tagline": "parry &#9851; riposte &#9851; recycle &#9851; repeat &#183; Riposte Laboratories Inc. &#183; 2026. This is the linear reading version of the investor deck; the full slide version lives at <a href=\"/deck/\">/deck/</a>.",
  "deck.cover.foot": "INVESTOR BRIEFING &#183; 2026 &#183; RIPOSTE LABORATORIES INC.",

  "deck.problem.h": "The Problem",
  "deck.problem.tag": "value thrown away intact",
  "deck.problem.h1": "We throw away material with <span class=\"hi\">most of its life left.</span>",
  "deck.problem.s1": "Of the 5,152 kt of plastic Canada discards each year, only ~6.5% is reprocessed into new material; the rest is buried or burned.<sup class=\"fn\"><a href=\"#fn1\">1</a></sup>",
  "deck.problem.s2": "No BC program buys post-industrial PS or ABS, the resins in every model kit. The nearest paying buyers sit roughly 4,000 km east, in Ontario.<sup class=\"fn\"><a href=\"#fn2\">2</a></sup>",
  "deck.problem.s3": "BC's producer-funded vape take-back is legislated but unbuilt; no processor is named yet, even in Quebec's live program.<sup class=\"fn\"><a href=\"#fn4\">4</a></sup>",
  "deck.problem.big": "The waste stream is not a disposal problem. It is <span class=\"hi\">mispriced inventory</span>: sorted, concentrated, and delivered to a predictable set of doors every day.",

  "deck.thesis.h": "The Thesis",
  "deck.thesis.tag": "the counter-attack",
  "deck.thesis.h1": "<b>riposte</b>: the <span class=\"hi\">counter-attack</span> after the parry.",
  "deck.thesis.big": "Recover material at the point it is discarded, re-engineer it into durable products, and return it to the same community. Short loops, no ocean freight, value captured locally.",

  "deck.model.h": "The Model",
  "deck.model.tag": "collect at the point of sale",
  "deck.model.h1": "Supply we don't have to <span class=\"hi\">go looking for.</span>",
  "deck.model.big": "We host drop-off bins at the businesses whose products become the waste; the material returns through its own front door, pre-sorted and clean. Post-industrial resin like this is cleaner and more homogeneous than curbside plastic, so it commands a premium<sup class=\"fn\"><a href=\"#fn3\">3</a></sup>; ours arrives free, because no BC buyer competes for PS or ABS today.<sup class=\"fn\"><a href=\"#fn2\">2</a></sup>",
  "deck.model.spec.h": "PARTNER NETWORK",
  "deck.model.spec.1": "<b>Hobby &amp; model stores</b>: gunpla runners; single-resin PS/ABS",
  "deck.model.spec.2": "<b>Phone / IT repair</b>: cells pulled during service",
  "deck.model.spec.3": "<b>Vape &amp; e-cig retailers</b>: spent disposables",
  "deck.model.spec.4": "<b>Electronics retail</b>: take-back volume (e.g. Best Buy)",
  "deck.model.spec.5": "Supply is clean, sorted, and free at the door",

  "deck.lines.h": "Product Lines",
  "deck.lines.tag": "two streams, one loop",
  "deck.lines.h1": "Two feedstocks. Two <span class=\"hi\">product lines.</span>",
  "deck.lines.s1.l": "Model-kit PS/ABS runners shredded, sorted, and injection-molded into durable goods; these are the resins BC has no buyer for,<sup class=\"fn\"><a href=\"#fn2\">2</a></sup> remade locally and sold locally.",
  "deck.lines.s2.l": "Reclaimed lithium cells tested, graded, and rebuilt into modular hexagonal power tiles: the flagship product.",
  "deck.lines.illus": "Plastic Works funds near-term revenue and the collection network; Project HEX is the venture-scale opportunity.",

  "deck.flagship.h": "Flagship: Project HEX",
  "deck.flagship.tag": "project hex &#183; modular reclaimed power",
  "deck.flagship.h1": "An energy tile, not a battery pack.",
  "deck.flagship.spec.h": "SPEC / HEX UNIT",
  "deck.flagship.spec.1": "6 &#215; cylindrical Li-ion, <b>45 &#215; 13 mm</b> &#183; reclaimed and graded",
  "deck.flagship.spec.2": "One cell per edge, wired <b>6S</b> (series)",
  "deck.flagship.spec.3": "6 &#215; 2.41 Wh = <b>14.46 Wh</b> per tile",
  "deck.flagship.spec.4": "Photovoltaic top face &#183; self-charging",
  "deck.flagship.spec.5": "Magnetic edges &#183; snap into tessellating arrays",
  "deck.flagship.spec.6": "Magnet-mount screen for interface + telemetry",

  "deck.vision.h": "The Vision",
  "deck.vision.tag": "a self-charging skin",
  "deck.vision.h1": "Hexagons tessellate. So we <span class=\"hi\">clad the whole home.</span>",
  "deck.vision.big": "Every tile generates, stores, and connects. Snap enough together and the array becomes the building's outer surface: a geodesic home that powers itself. The array scales without gaps, wraps compound curves, and grows one reclaimed tile at a time. The waste stream becomes distributed energy infrastructure.",

  "deck.whynow.h": "Why Now",
  "deck.whynow.tag": "the tailwinds line up",
  "deck.whynow.h1": "The moment for <span class=\"hi\">reclaimed, distributed power.</span>",
  "deck.whynow.pill1": "BC vape EPR legislated for Oct 2027; plans due Dec 2026<sup class=\"fn\"><a href=\"#fn4\">4</a></sup>",
  "deck.whynow.pill2": "Clean post-industrial resin worth multiples of curbside bales<sup class=\"fn\"><a href=\"#fn3\">3</a></sup>",
  "deck.whynow.pill3": "Virgin ABS ~US$2,000/t; PS ~US$1,350/t<sup class=\"fn\"><a href=\"#fn5\">5</a></sup>",
  "deck.whynow.pill4": "&gt;99% of BC's recycled plastic already stays in-province<sup class=\"fn\"><a href=\"#fn6\">6</a></sup>",
  "deck.whynow.pill5": "448 waste-facility fires in 2025 ($2.5B); vapes a named driver<sup class=\"fn\"><a href=\"#fn7\">7</a></sup>",
  "deck.whynow.pill6": "Commercial recycled-PS demand opening in the east<sup class=\"fn\"><a href=\"#fn8\">8</a></sup>",
  "deck.whynow.big": "Feedstock is abundant and free where no one else pays for it; regulation and buyers are arriving on a fixed clock. Riposte sits exactly where those curves cross.",

  "deck.market.h": "Market",
  "deck.market.tag": "illustrative &#183; placeholder sizing",
  "deck.market.h1": "A large market, entered <span class=\"hi\">one bin at a time.</span>",
  "deck.market.s1.l": "Total: distributed energy storage and recycled-material goods",
  "deck.market.s2.l": "Serviceable: modular home power and reclaimed goods in region; BC EPR already captures roughly 315,000 t of plastics per year<sup class=\"fn\"><a href=\"#fn9\">9</a></sup>",
  "deck.market.s3.l": "Obtainable: target within the first [N] years via partner network",
  "deck.market.illus": "&#9888; Illustrative placeholders. Replace [TAM]/[SAM]/[SOM] and the target window with your researched figures before sending.",

  "deck.biz.h": "Business Model",
  "deck.biz.tag": "how it makes money",
  "deck.biz.h1": "Free feedstock. <span class=\"hi\">Multiple revenue lines.</span>",
  "deck.biz.pill1": "HEX tile &amp; array sales",
  "deck.biz.pill2": "Plastic Works goods",
  "deck.biz.pill3": "Partner-branded take-back",
  "deck.biz.pill4": "IP / design licensing",
  "deck.biz.p": "Collection costs near zero because partners host the bins, and the PS/ABS we take has no competing local buyer.<sup class=\"fn\"><a href=\"#fn2\">2</a></sup> Margin is driven by how cheaply reclaimed cells and runners convert into finished product.",
  "deck.biz.spec.h": "HEX TILE &#183; UNIT ECONOMICS (ILLUSTRATIVE)",
  "deck.biz.spec.1": "Reclaimed cells (6): <b>$[__]</b> &#183; sourced free, graded in-house",
  "deck.biz.spec.2": "PV top + housing + magnets: <b>$[__]</b>",
  "deck.biz.spec.3": "Assembly + test labour: <b>$[__]</b>",
  "deck.biz.spec.4": "Landed COGS / tile: <b>$[__]</b>",
  "deck.biz.spec.5": "Target price / tile: <b>$[__]</b>",
  "deck.biz.spec.6": "Gross margin: <b>[__]%</b>",
  "deck.biz.illus": "&#9888; Illustrative unit economics; replace with real BOM, labour, and pricing figures.",

  "deck.roadmap.h": "Roadmap",
  "deck.roadmap.tag": "prototype &#8594; production &#8594; pilot home",
  "deck.roadmap.h1": "From bench unit to a <span class=\"hi\">powered dome.</span>",
  "deck.roadmap.r1.ph": "Phase 0", "deck.roadmap.r1.d": "Working HEX prototype, patent filed, first drop-off partners signed. Plastic Works generating early revenue.",
  "deck.roadmap.r2.ph": "Phase 1", "deck.roadmap.r2.d": "Pilot partner network across hobby, repair &amp; vape retail. Cell grading line + small-batch tile assembly.",
  "deck.roadmap.r3.ph": "Phase 2", "deck.roadmap.r3.d": "Limited production run of HEX arrays; certification &amp; safety testing; first array installations.",
  "deck.roadmap.r4.ph": "Phase 3", "deck.roadmap.r4.d": "Geodesic pilot home fully clad in HEX; licensing conversations; regional network scale-out.",
  "deck.roadmap.now": "NOW",
  "deck.roadmap.illus": "&#9888; Replace bracketed dates with your real timeline.",

  "deck.team.h": "Team &amp; Moat",
  "deck.team.tag": "why riposte wins",
  "deck.team.h1": "Defensible on <span class=\"hi\">supply, IP, and brand.</span>",
  "deck.team.s1.n": "Supply", "deck.team.s1.l": "A partner network that supplies clean, sorted feedstock at no cost; difficult for a newcomer to replicate.",
  "deck.team.s2.n": "IP", "deck.team.s2.l": "Patent-pending HEX architecture: edge cells, solar face, magnetic tessellation.",
  "deck.team.s3.n": "Brand", "deck.team.s3.l": "A distinct identity (esh, the emblem) that turns recycling into a product people want on their wall.",
  "deck.team.illus": "Add founder and team bios here: names, relevant experience, and advisors.",

  "deck.ask.h": "The Ask",
  "deck.ask.tag": "illustrative &#183; your numbers here",
  "deck.ask.h1": "Raising to reach <span class=\"hi\">production.</span>",
  "deck.ask.raising.k": "Raising", "deck.ask.raising.v": "$[____] &#183; [seed]",
  "deck.ask.val.k": "Valuation / terms", "deck.ask.val.v": "$[____] [cap / pre-money]",
  "deck.ask.runway.k": "Runway", "deck.ask.runway.v": "[__] months &#8594; Phase [__]",
  "deck.ask.use.h": "Use of funds", "deck.ask.use.note": "(illustrative)",
  "deck.ask.use.1": "R&amp;D &#183; certification",
  "deck.ask.use.2": "Production line",
  "deck.ask.use.3": "Network &amp; ops",
  "deck.ask.use.4": "Team",
  "deck.ask.illus": "&#9888; Every figure on this slide is a placeholder. Set the raise, terms, runway, and allocation before sharing.",

  "deck.close.h": "Get in touch",
  "deck.close.tag": "parry the waste. riposte with product.",
  "deck.close.lede": "Parry the waste. <span class=\"hi\">Riposte with product.</span>",
  "deck.close.foot": "RIPOSTE LABORATORIES INC. &#183; CONFIDENTIAL &#183; 2026",

  "deck.sources.h": "Sources &amp; notes",
  "deck.sources.foot": "Prices are indicative published figures as of the July 2026 research, not quotes; company acceptance terms should be confirmed directly.",
  "dsrc.1": "Statistics Canada &#183; Physical flow account for plastic material, 2022 (released 2026): 5,152 kt discarded, roughly 6.5% reprocessed. <a href=\"https://www150.statcan.gc.ca/n1/daily-quotidien/260326/dq260326e-eng.htm\">statcan.gc.ca</a>",
  "dsrc.2": "Recycling Council of BC &#183; no set BC program accepts plastics from business; Merlin Plastics' buy list omits PS/ABS; the nearest published PS/ABS buyers are in Ontario (EPL Plastics, Kal-Polymers). <a href=\"https://rcbc.ca/our-faqs/where-can-i-recycle-plastics-from-my-business/\">rcbc.ca</a> &#183; <a href=\"https://merlinplastics.com/\">merlinplastics.com</a>",
  "dsrc.3": "Association of Plastic Recyclers (post-industrial resin is cleaner, more homogeneous, higher value) and indicative buyer ranges (Seraphim Plastics) vs post-consumer bale averages (SMP / Resource Recycling). <a href=\"https://plasticsrecycling.org/resources/is-all-recycled-material-created-equal/\">plasticsrecycling.org</a>",
  "dsrc.4": "Recycling Regulation, B.C. Reg. 449/2004 (vapes added Nov 2025; approved plan required Oct 1, 2027, submissions due Dec 15, 2026); Call2Recycle draft 2025&#8211;2029 BC plan. Quebec's is the only operating program; no processor is publicly named. <a href=\"https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/449_2004\">bclaws.gov.bc.ca</a> &#183; <a href=\"https://call2recycle.ca/british-columbia/\">call2recycle.ca</a>",
  "dsrc.5": "ChemAnalyst &#183; US virgin resin pricing, 2026: ABS approximately US$1,987/t; polystyrene approximately US$1,348/t. <a href=\"https://www.chemanalyst.com/Pricing-data/acrylonitrile-butadiene-styrene-19\">chemanalyst.com</a>",
  "dsrc.6": "Recycle BC &#183; 2024 reporting: over 99% of collected plastics processed in-province (Merlin Plastics the principal processor). <a href=\"https://recyclebc.ca/learn/our-impact/plastic-recycling/\">recyclebc.ca</a>",
  "dsrc.7": "Fire Rover via Resource Recycling &#183; 448 publicly reported fires at US and Canadian waste and recycling facilities in 2025 (approximately $2.5B in damages); vaping devices cited as a driver. <a href=\"https://resource-recycling.com/e-scrap/2026/03/27/report-pegs-fire-losses-at-2-5b-in-us-and-canada-recycling-industry/\">resource-recycling.com</a>",
  "dsrc.8": "Global Insulation &#183; UpSolv (formerly Polystyvert) began commercial recycled-PS production in February 2026 (approximately 9,000 t/yr), sourcing external feedstock. <a href=\"https://www.globalinsulation.com/news/2185-upsolv-launches-commercial-recycled-polystyrene-resin-production\">globalinsulation.com</a>",
  "dsrc.9": "Province of BC &#183; EPR Five-Year Action Plan 2021&#8211;2026: approximately 315,000 t of plastics per year captured across BC EPR programs (figure originates c. 2019 and may count plastic-containing products). <a href=\"https://www2.gov.bc.ca/assets/gov/environment/waste-management/recycling/recycle/extended_producer_five_year_action_plan.pdf\">www2.gov.bc.ca</a>"
};
